### ISSUE TITLE
Windows 10 creators update breaks parser

### ISSUE THREAD

**Issue by EricZimmerman** [mandiant/ShimCacheParser#14]
due to changes in the binary data in creators update, code to handle windows 10 needs to be updated.

if first 4 bytes == 0x30, handle as is, if == 0x34, need to index into the data 4 more bytes. Everything after that works the same way

More detail here:

https://binaryforay.blogspot.com/2017/03/windows-10-creators-update-vs-shimcache.html

**Comment by EricZimmerman** [comment]
you can get the ISO for creators update here

http://www.windowscentral.com/windows-10-creators-update-build-15063-iso-files-now-available-download

**Comment by williballenthin** [comment]
@EricZimmerman Do you know how the fields in the header are shifted? Is there simply a new 32bit field appended to the existing header, or inserted somewhere in the middle?

**Comment by EricZimmerman** [comment]
once you shift 4 bytes, everything else parsed the same. I haven't seen any other changes in my initial round of testing and coding for what is inside the record itself. I didn't break down or try to track down the new 4 bytes as of yet. there is a counter in there for the # of entries, but that has been in both formats

in my code, I added a check for the version (first 4 bytes) and adjusted the initial offset based on whether it was 0x30 or 0x34. nothing else needed to be changed for all my unit tests to pass

**Comment by EricZimmerman** [comment]
I do have screenshots of the old and new format on the blog post, so it may drop right out from those. i pull the expected entry count but do not do much with the other stuff.

**Comment by williballenthin** [comment]
As a fix, we should consider using the value of `CacheEntryNt6.wLength` on line [457](https://github.com/mandiant/ShimCacheParser/blob/master/ShimCacheParser.py#L457) to correctly compute the start of the cache entry data.

I think there is also a change we need to make to correctly find the magic. Studying this now.

**Comment by EricZimmerman** [comment]
this is the offset that would do it

WIN10_STATS_SIZE = 0x30

**Comment by williballenthin** [comment]
As a fix, probably just need to add an additional case around [here](https://github.com/mandiant/ShimCacheParser/blob/master/ShimCacheParser.py#L265) when `WIN10_STATS_SIZE` is 0x34, which we might call `WIN10CREATORS_STATS_SIZE` or something...

**Comment by williballenthin** [comment]
@EricZimmerman do you have a creator's update hive/appcompat value you can share?

**Comment by EricZimmerman** [comment]
when you fall into the possible windows 10 case, just set WIN10_STATS_SIZE to be equal to the 32-bit int at the start of the data. once that is set everything else will work as is

**Comment by PoorBillionaire** [comment]
PR #19 should resolve this. I continued with the script's current method of hard-coding the relevant values. Straying from the established style probably isn't worth it for a quick fix.

--
Adam

**Comment by PoorBillionaire** [comment]
Noticed that @EricZimmerman referenced this issue in another project. Eric, this one can be closed.
